import t03performance/dependency/constructor
import t03performance/dependency/setter
import t03performance/dependency/interfaceinjection
import t03performance/dependency/fibonacci
import t03performance/dependency/square