import performance/dependency/constructor
import performance/dependency/setter
import performance/dependency/interfaceinjection
import performance/dependency/fibonacci
import performance/dependency/square